apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: node-labeller-sa

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: nodes-reader-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: node-controller
subjects:
- kind: ServiceAccount
  name: node-labeller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: nodes-reader-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: node-labeller
spec:
  serviceAccountName: node-labeller-sa
  containers:
  - name: node-labeller-container
    image: ramzichbl/k8-node-labeller
    env:
    - name: NODES_LABEL
      value: "worker-node"

